version: '3'

services:
  postgresql:
    image: bitnami/postgresql:13
    shm_size: 256m
    volumes:
      - postgresql_data:/bitnami/postgresql
      - ./etc/postgresql/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./data/vocabulary:/data/vocabulary
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - PGPASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=ohdsi
    restart: unless-stopped

  jupyterhub:
    restart: unless-stopped
    image: thehyve/ohdsi-etl-jupyterhub:1.3.0
    build:
      context: images/jupyterhub
      args:
        JUPYTERHUB_VERSION: "1.3.0"
    depends_on:
      - jupyterhub-postgresql
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "jupyterhub_data:/data"
    ports:
      - "8000:8000"
    environment:
      DATA_VOLUME_CONTAINER: '/data'
      DOCKER_SPAWN_CMD: 'start-singleuser.sh --SingleUserNotebookApp.default_url=/lab'
      DOCKER_NOTEBOOK_IMAGE: 'thehyve/ohdsi-jupyter-notebook'
      DOCKER_NETWORK_NAME: "${COMPOSE_PROJECT_NAME}_default"
      DOCKER_NOTEBOOK_DIR: '/home/jovyan'
      DATA_VOLUME_CONTAINER: '/data/'
      POSTGRES_HOST: 'jupyterhub-postgresql'
      POSTGRES_DB: jupyterhub
      POSTGRES_USER: jupyterhub
      POSTGRES_PASSWORD: ${JUPYTERHUB_POSTGRESQL_PASSWORD}
      JUPYTER_PASSWORD: ${JUPYTERHUB_PASSWORD}

  jupyterhub-postgresql:
    image: bitnami/postgresql:13
    environment:
      POSTGRES_DB: jupyterhub
      POSTGRES_USER: jupyterhub
      POSTGRES_PASSWORD: ${JUPYTERHUB_POSTGRESQL_PASSWORD}
    volumes:
      - jupyterhub_data:/bitnami/postgresql
    restart: unless-stopped

volumes:
  postgresql_data:
    driver: local
  keycloak_data:
    driver: local
  jupyterhub_data:
    driver: local
